stages:
  - Static_test
  - Build
  - Unit_Testing

#Проверка кодировки файлов с расширением .m .cpp .h на соответствие UTF-8
Unicode:
  stage: Static_test
  tags:
    - docker
  image: $DOCKER_REGISTRY/$DOCKER_REPO/gcc
  script:
    - mkdir -p pipeline/pipeline_result
    - touch encoding_error_list.txt pipeline/pipeline_result
    - bash pipeline/pipeline_scripts/unicode_check.sh
  allow_failure: true
  artifacts:
    expire_in: 48 hour
    when: on_failure
    paths:
      - pipeline/pipeline_result

Doxygen:
  stage: Static_test
  tags:
    - docker
  image: $DOCKER_REGISTRY/$DOCKER_REPO/greenbone/doxygen:latest
  script:
    - mkdir -p pipeline/pipeline_result
    - bash ./pipeline/pipeline_scripts/doxygen_test.sh
  allow_failure: true
  artifacts:
    expire_in: 48 hour
    when: always
    paths:
      - pipeline/pipeline_result

Clang:
  stage: Static_test
  tags:
    - docker
  image: $DOCKER_REGISTRY/$DOCKER_REPO/jhasse/clang-tidy:latest
  #image: jhasse/clang-tidy
  script:
    - mkdir -p pipeline/pipeline_result
    - bash ./pipeline/pipeline_scripts/Clang_test.sh
  allow_failure: true
  artifacts:
    expire_in: 48 hour
    when: always
    paths:
      - pipeline/pipeline_result

#Сборка проекта GCC
GCC_build:
  stage: Build
  tags:
    - docker
  image: $DOCKER_REGISTRY/$DOCKER_REPO/gcc_cmake_boost_eigen_gtest:latest
  script:
    - bash pipeline/pipeline_scripts/gccbuild.sh
  allow_failure: false
  artifacts:
    expire_in: 24 hour
    when: always
    paths:
      - pipeline/pipeline_result/build_gcc_result
      - Libs/GCC

#Сборка проекта Clang
Clang_build:
  stage: Build
  tags:
    - dev-build-clang
  script:
    - cd pipeline/pipeline_scripts/
    - .\clangbuild.ps1
  allow_failure: false
  artifacts:
    expire_in: 24 hour
    when: always
    paths:
      - pipeline/pipeline_result/build_clang_result
      - Libs/Clang

#Сборка проекта MinGW
MinGW_build:
  stage: Build
  tags:
    - ktk-dev-build
  script:
    - cd pipeline/pipeline_scripts/
    - .\mingwbuild.ps1
  allow_failure: false
  artifacts:
    expire_in: 24 hour
    when: always
    paths:
      - pipeline/pipeline_result/build_mingw_result
      - Libs/MinGW

# Запуск тестов с использованием GTest
fs_tests:
  stage: Unit_Testing
  tags:
    - docker
  image: $DOCKER_REGISTRY/$DOCKER_REPO/gcc_cmake_boost_eigen_gtest:latest
  script:
    - bash pipeline/pipeline_scripts/tests_start.sh GCC fs_tests
  needs: [GCC_build]
  dependencies: [GCC_build]
  allow_failure: false
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - branches.txt
      - pipeline/pipeline_result
      - Libs